### ISSUE TITLE
Email messages does't work

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#44]
We have two different email messages:
1. for admins, when someone submits a new task
2. for users, when admin approve task

Now our messages doesn't deliver, we need to fix it

**Updated**

```
2017-01-30T13:10:12.291479+00:00 app[worker.1]: 4 TID-ot9kf66bk WARN: Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
2017-01-30T13:10:12.291541+00:00 app[worker.1]: 4 TID-ot9kf66bk WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `initialize'
2017-01-30T13:10:12.291543+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `open'
2017-01-30T13:10:12.291545+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket'
2017-01-30T13:10:12.291546+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start'
2017-01-30T13:10:12.291546+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
2017-01-30T13:10:12.291547+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
2017-01-30T13:10:12.291548+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start'
2017-01-30T13:10:12.291548+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
2017-01-30T13:10:12.291549+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
2017-01-30T13:10:12.291550+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
2017-01-30T13:10:12.291551+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:239:in `deliver'
2017-01-30T13:10:12.291551+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:222:in `deliver'
2017-01-30T13:10:12.291552+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:186:in `deliver'
2017-01-30T13:10:12.291553+00:00 app[worker.1]: /app/lib/ossboard/workers/new_task_notification_worker.rb:8:in `block in perform'
2017-01-30T13:10:12.291553+00:00 app[worker.1]: /app/lib/ossboard/workers/new_task_notification_worker.rb:7:in `each'
2017-01-30T13:10:12.291554+00:00 app[worker.1]: /app/lib/ossboard/workers/new_task_notification_worker.rb:7:in `perform'
2017-01-30T13:10:12.291555+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
2017-01-30T13:10:12.291555+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
2017-01-30T13:10:12.291556+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
2017-01-30T13:10:12.291556+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
2017-01-30T13:10:12.291557+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2017-01-30T13:10:12.291558+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2017-01-30T13:10:12.291558+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-30T13:10:12.291559+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2017-01-30T13:10:12.291559+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
2017-01-30T13:10:12.291560+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2017-01-30T13:10:12.291560+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-30T13:10:12.291561+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2017-01-30T13:10:12.291561+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
2017-01-30T13:10:12.291562+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
2017-01-30T13:10:12.291562+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
2017-01-30T13:10:12.291563+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
2017-01-30T13:10:12.291564+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
2017-01-30T13:10:12.291564+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
2017-01-30T13:10:12.291565+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
2017-01-30T13:10:12.291565+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
2017-01-30T13:10:12.291566+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by charlie-wasp** [comment]
I has been trying to fix that, but hit a dead end.

I started sidekiq with the command `sidekiq -r ./config/environment.rb` and that is, what I've got on mail send:

```
2017-01-26T15:11:27.583Z 10021 TID-gn79sd9jg NewTaskNotificationWorker JID-d08303bfe924a1c96a59c1a8 INFO: fail: 0.001 sec
2017-01-26T15:11:27.584Z 10021 TID-gn79sd9jg WARN: {"context":"Job raised exception","job":{"class":"NewTaskNotificationWorker","args":[3],"retry":true,"queue":"default","jid":"d08303bfe924a1c96a59c1a8","created_at":1485443394.4538486,"enqueued_at":1485443487.5801716,"error_message":"Not loaded","error_class":"RuntimeError","failed_at":1485443394.4553835,"retry_count":1,"retried_at":1485443487.5827596},"jobstr":"{\"class\":\"NewTaskNotificationWorker\",\"args\":[3],\"retry\":true,\"queue\":\"default\",\"jid\":\"d08303bfe924a1c96a59c1a8\",\"created_at\":1485443394.4538486,\"enqueued_at\":1485443487.5801716,\"error_message\":\"Not loaded\",\"error_class\":\"RuntimeError\",\"failed_at\":1485443394.4553835,\"retry_count\":0}"}
2017-01-26T15:11:27.584Z 10021 TID-gn79sd9jg WARN: RuntimeError: Not loaded
2017-01-26T15:11:27.584Z 10021 TID-gn79sd9jg WARN: /app/vendor/bundle/ruby/2.3.0/gems/hanami-model-0.7.0/lib/hanami/model.rb:70:in `container'
/app/vendor/bundle/ruby/2.3.0/gems/hanami-model-0.7.0/lib/hanami/repository.rb:144:in `container'
/app/vendor/bundle/ruby/2.3.0/gems/hanami-model-0.7.0/lib/hanami/repository.rb:360:in `initialize'
/app/lib/ossboard/workers/new_task_notification_worker.rb:5:in `new'
/app/lib/ossboard/workers/new_task_notification_worker.rb:5:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```
As we can see, problem is that `UserRepository` is not _loaded_ in `NewTaskNotificationWorker#perform`. I am not familiar with Hanami architecture, so I'm stuck on that, I don't know what it really means. I can guess that app wasn't properly launched, but I don't know, how to fix that. Moreover internet search gave me a couple blog posts, which authors do everything the same as me.

@davydovanton can you help me out a little? Maybe some hint? Or should I ask Hanami community?

**Comment by davydovanton** [comment]
hey, thanks for research 👍 
I think we can load app in sidekiq config but I need time for checking this idea

**Comment by charlie-wasp** [comment]
FYI I already had to add `require_relative './initializers/sidekiq.rb'` in `environment.rb` to launch Sidekiq at all, so I guess command in `Procfile` may be wrong

**Comment by davydovanton** [comment]
@charlie-wasp we can't do it because all initialize files (like redis) will load after this line. That's why we will have redis error 😞

I think I need to rewrite sidekiq configuration logic and replace sidekiq from initializer

**Comment by charlie-wasp** [comment]
I will be glad to help. I will continue trying to crack this case, if you don't mind :)

**Comment by davydovanton** [comment]
Yes, of course 🌟
You can use this guide (I think it will be helpful for you)
http://www.strauss.io/blog/2016-use-sidekiq-with-hanami.html

**Comment by charlie-wasp** [comment]
Thanks, I read it already :)

**Comment by davydovanton** [comment]
@charlie-wasp hey, any updates? Can I help you with this issue? :)

**Comment by davydovanton** [comment]
@charlie-wasp hey, I fixed sidekiq server (require boot file, you can read more [here](https://github.com/hanami/hanami/pull/720))

**Comment by charlie-wasp** [comment]
@davydovanton hello, sorry, hadn't time recently :( So this problem is solved? Or solution should be verified?

**Comment by charlie-wasp** [comment]
@davydovanton done a little of work, Sidekiq again gave me hard time with connection pools, I opened PR https://github.com/davydovanton/ossboard/pull/62 for corrections, these changes made sidekiq work for me (at last).

This task became the task about sidekiq fixes :)

But speaking about email, I see in your original comment there was connection problem with the 25 port, but now I see, that in production Mailgun will be used. So original error is irrelevant already, is it right?

**Comment by davydovanton** [comment]
Fixed
